version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install Package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q .[dev] codecov
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest \
              --strict \
              --cov=spml \
              --junitxml=test-reports/junit.xml \
              spml
            codecov
      - run:
          name: Style Check
          command: |
            . venv/bin/activate
            flake8 spml

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test
